const mongoose = require('mongoose');

const schoolSchema = new mongoose.Schema({
    schoolId: {
        type: String,
        unique: true,
        sparse: true,  // Allow null during creation, will be generated by pre-save
        index: true
    },
    name: {
        type: String,
        required: [true, 'School name is required'],
        trim: true,
        maxlength: [200, 'School name cannot exceed 200 characters']
    },
    code: {
        type: String,
        unique: true,
        index: true
        // Format: First letter + Last letter + number (e.g., SL1, SM2)
    },
    codeNumber: {
        type: Number,
        index: true
        // Numeric version of the suffix for proper sorting (e.g., 1, 2)
    },
    address: {
        type: String,
        trim: true,
        default: ''
    },
    phone: {
        type: String,
        trim: true,
        default: ''
    },
    email: {
        type: String,
        trim: true,
        lowercase: true,
        default: ''
    },
    principalName: {
        type: String,
        trim: true,
        default: ''
    },
    studentCount: {
        type: Number,
        default: 0
    },
    isActive: {
        type: Boolean,
        default: true,
        index: true
    },
    createdAt: {
        type: Date,
        default: Date.now
    },
    updatedAt: {
        type: Date,
        default: Date.now
    }
}, {
    timestamps: true
});

// Auto-generate school code and ID before validation
schoolSchema.pre('validate', async function (next) {
    // Only for new documents
    if (!this.isNew) {
        return next();
    }

    try {
        // 1. Generate School Code (NS1, etc.)
        if (!this.code) {
            const words = this.name.trim().split(/\s+/);
            const firstLetter = words[0].charAt(0).toUpperCase();
            const lastLetter = words[words.length - 1].charAt(0).toUpperCase();
            const baseCode = firstLetter + lastLetter;

            // Find the highest codeNumber for this specific base code
            // We search for codes that start with the base letters
            const lastSchoolWithSameBase = await this.constructor.findOne({
                code: new RegExp(`^${baseCode}\\d+$`)
            }).sort({ codeNumber: -1 }).lean();

            let nextNumber = 1;
            if (lastSchoolWithSameBase && lastSchoolWithSameBase.codeNumber) {
                nextNumber = lastSchoolWithSameBase.codeNumber + 1;
            } else if (lastSchoolWithSameBase) {
                // Fallback for existing data that might not have codeNumber yet
                const match = lastSchoolWithSameBase.code.match(/\d+$/);
                if (match) {
                    nextNumber = parseInt(match[0]) + 1;
                }
            }

            this.codeNumber = nextNumber;
            this.code = `${baseCode}${nextNumber}`;
        }

        // 2. Generate School ID (01, 02, etc.)
        if (!this.schoolId) {
            const lastSchool = await this.constructor.findOne({})
                .sort({ createdAt: -1 })
                .lean();

            let nextId = 1;
            if (lastSchool && lastSchool.schoolId) {
                const currentId = parseInt(lastSchool.schoolId);
                if (!isNaN(currentId)) {
                    nextId = currentId + 1;
                }
            }

            this.schoolId = String(nextId).padStart(2, '0');
        }

        next();
    } catch (error) {
        console.error('Error in school pre-validate hook:', error);
        next(error);
    }
});

module.exports = mongoose.model('School', schoolSchema);
